spring:
  # profiles: useronly
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update   # 초기엔 create/update 편한 걸로
    open-in-view: false
    show-sql: true
  flyway:
    enabled: false
  liquibase:
    enabled: false

server:
  port: 5000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# JWT 보안을 사용한다면 필요한 최소치
jwt:
  secret: ${JWT_SECRET_KEY}   # 실제 비밀키로 교체
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 1209600

# 필요 시 기능 플래그로 다른 모듈 끄기
feature:
  quiz:
    enabled: false
